FROM debian:testing-slim

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set up renderer user
RUN adduser --disabled-password --gecos "" renderer

RUN apt-get update
RUN apt-get install -y screen vim sudo wget gnupg2 apt-transport-https ca-certificates curl 

#install nodejs
RUN wget --quiet -O - https://deb.nodesource.com/setup_14.x | bash - \
  && apt-get update \
  && apt-get install -y nodejs

RUN apt-get install -y --no-install-recommends \
  apache2-dev \
  autoconf \
  automake \
  cmake \
  g++ \
  gdal-bin \
  git-core \
  libboost-dev \
  libboost-filesystem-dev \
  libboost-system-dev \
  libbz2-dev \
  libexpat1-dev \
  liblua5.3-dev\
  libmapnik-dev \
  libpq-dev \
  libproj-dev \
  libtool-bin \
  lua5.3 \
  make \
  osmium-tool \
  osmosis \
  postgresql-client \
  python \
  python3-lxml \  
  python3-pip \
  python3-psycopg2 \
  python3-shapely \
  zlib1g-dev 

# Install python libraries
RUN pip3 install requests \ 
  && pip3 install pyyaml

# Install latest osm2pgsql
RUN mkdir -p /home/renderer/src \
  && cd /home/renderer/src \
  && git clone -b master https://github.com/openstreetmap/osm2pgsql.git --depth 1 \
  && cd /home/renderer/src/osm2pgsql \
  && rm -rf .git \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install \
  && mkdir /nodes \
  && chown renderer:renderer /nodes \
  && rm -rf /home/renderer/src/osm2pgsql

# Install mod_tile and renderd
RUN mkdir -p /home/renderer/src \
  && cd /home/renderer/src \
  && git clone -b switch2osm https://github.com/mariocki/mod_tile.git --depth 1 \
  && cd mod_tile \
  && rm -rf .git \
  && ./autogen.sh \
  && ./configure \
  && make \
  && make install \
  && ldconfig \
  && cd ..

# Configure stylesheet
RUN npm install -g carto

RUN apt-get clean autoclean -y \
  && apt-get autoremove --yes \
  && rm -rf /var/lib/{apt,dpkg,cache,log}

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

# Copy update scripts
COPY ./scripts/import/openstreetmap-tiles-update-expire /usr/bin/
RUN chmod +x /usr/bin/openstreetmap-tiles-update-expire \
  && mkdir -p /var/log/tiles \
  && chmod a+rw /var/log/tiles 

# Install trim_osc.py helper script
# https://raw.githubusercontent.com/Zverik/regional/master/trim_osc.py
COPY ./scripts/import/trim_osc.py /usr/local/bin/
RUN chmod a+x /usr/local/bin/trim_osc.py

# Start running
COPY ./scripts/import/run.sh /
COPY ./openstreetmap-carto/indexes.sql /
RUN chmod +x /run.sh
ENTRYPOINT ["/run.sh"]
CMD []

