FROM mariocki/osm-server-core:v1 

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
  gdal-bin \
  python3-pip \
  patch 

# Install python libraries
RUN pip3 install requests \ 
  && pip3 install pyyaml elevation

RUN apt-get clean autoclean -y \
  && apt-get autoremove --yes \
  && rm -rf /var/lib/{apt,dpkg,cache,log}

RUN mkdir -p /var/log/tiles \
  && chmod -R a+rw /var/log/tiles

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

# Copy update scripts
# https://raw.githubusercontent.com/SomeoneElseOSM/mod_tile/blob/master/openstreetmap-tiles-update-expire
COPY ./scripts/maps/openstreetmap-tiles-update-expire /usr/local/bin/openstreetmap-tiles-update-expire-orig

# patch elevation to allow a reasonable number of downloads
COPY ./patches/elevation.patch /elevation.patch
RUN cd /usr/local/lib/python3.9/dist-packages/elevation \
  && patch < /elevation.patch

# copy indexes just in case
COPY ./openstreetmap-carto/indexes.psql /

# Start running
COPY ./scripts/import/run.sh /

RUN chmod +x /run.sh
ENTRYPOINT ["/run.sh"]
CMD []

