version: "3.9"

networks:
  my_network:
    external: false

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.osm-server-db
    image: mariocki/osm-server-db:latest
    shm_size: "1gb"
    volumes:
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/gis:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: "-c config_file=/etc/postgresql/postgresql.conf"
    networks:
      - my_network
  core:
    build:
      context: .
      dockerfile: Dockerfile.osm-server-core
    image: mariocki/osm-server-core:latest
    env_file:
      - .env
  import:
    build:
      context: .
      dockerfile: Dockerfile.osm-server-import
    image: mariocki/osm-server-import:latest
    volumes:
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/mod_tile:/var/lib/mod_tile
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/data:/data
      - ./openstreetmap-carto:/openstreetmap-carto
    depends_on:
      - db
    env_file:
      - .env
    #command: --create
    networks:
      - my_network
  maps:
    image: mariocki/osm-server-maps:latest
    build:
      context: .
      dockerfile: Dockerfile.osm-server-maps
    volumes:
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/mod_tile:/var/lib/mod_tile
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/munin:/var/lib/munin
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/data:/data
      - ./openstreetmap-carto:/openstreetmap-carto
    depends_on:
      - core
      - db
    ports:
      - "8080:80"
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my_network
  pghero:
    image: ankane/pghero
    depends_on:
      - db
    ports:
      - "8081:3000"
    env_file:
      - .env
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8082:80"
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - db
  kosmtik:
    image: mariocki/osm-server-kosmtik:latest
    build:
      context: .
      dockerfile: Dockerfile.osm-server-kosmtik
    volumes:
      - /mnt/wsl/PhysicalDrive4p1/osm-maps/mod_tile:/var/lib/mod_tile
      - ./openstreetmap-carto:/openstreetmap-carto
    depends_on:
      - db
    ports:
      - "6789:6789"
    env_file:
      - .env
    networks:
      - my_network
