version: "3.9"

networks:
  my_network:
    external: false

services:
  import:
    build:
      context: .
      dockerfile: Dockerfile.import
    image: mariocki/osm-server-import:v1
    volumes:
      - ~/osm-maps/mod_tile:/var/lib/mod_tile
      - ~/osm-maps/data.osm.pbf:/data.osm.pbf
      - ~/osm-maps/data.poly:/data.poly
      - ./openstreetmap-carto:/openstreetmap-carto
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my_network
  kosmtik:
    image: mariocki/osm-server-kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile.kosmtik
    volumes:
      - ./openstreetmap-carto:/openstreetmap-carto
    depends_on:
      - db
    ports:
      - "6789:6789"
    env_file:
      - .env
    networks:
      - my_network
  maps:
    image: mariocki/osm-server-maps:v1
    build:
      context: .
      dockerfile: Dockerfile.maps
    volumes:
      - ~/osm-maps/mod_tile:/var/lib/mod_tile
      - ~/osm-maps/munin:/var/lib/munin
      - ./openstreetmap-carto:/openstreetmap-carto
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - my_network
  db:
    build:
      context: .
      dockerfile: Dockerfile.psql
    image: mariocki/osm-server-db:v1
    shm_size: "1gb"
    volumes:
      - ~/osm-maps/gis:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: "-c config_file=/etc/postgresql/postgresql.conf"
    networks:
      - my_network
  pghero:
    build:
      context: .
      dockerfile: Dockerfile.pghero
    image: mariocki/osm-server-pghero:v1
    depends_on:
      - db
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - my_network
