#!/bin/bash

set -e

export PATH=.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ACCOUNT=renderer

BASE_DIR=/var/lib/mod_tile
LOG_DIR=/var/log/tiles/
WORKOSM_DIR=$BASE_DIR/.osmosis

OSMOSISLOG=$LOG_DIR/osmosis.log
RUNLOG=$LOG_DIR/run.log

m_info() {
    echo "[$(date +"%Y-%m-%d %H:%M:%S")] $$ $1" | tee -a "$RUNLOG" | logger
}

if [ $# -eq 1 ]; then
    m_info "Initialising Osmosis replication system to $1"
    mkdir -p $WORKOSM_DIR
    osmosis --read-replication-interval-init workingDirectory=$WORKOSM_DIR 2>&1 | tee -a "$OSMOSISLOG" | logger
    wget "https://replicate-sequences.osm.mazdermind.de/?"$1"T00:00:00Z" -O $WORKOSM_DIR/state.txt
    mv $WORKOSM_DIR/configuration.txt $WORKOSM_DIR/configuration_orig.txt
    sed "s!baseUrl=http://planet.openstreetmap.org/replication/minute!baseUrl=https://planet.openstreetmap.org/replication/minute!" $WORKOSM_DIR/configuration_orig.txt >$WORKOSM_DIR/configuration.txt
fi
